'use client';
import './globals.css';
import { QueryClientProvider } from 'react-query';
import { queryClient } from './lib/queryClient';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          { children }
        </QueryClientProvider>
      </body>
    </html>
  )
}
